# Generated by Django 3.2 on 2022-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='ARS', max_length=3, null=True),
        ),
    ]
