# Generated by Django 3.2 on 2022-09-12 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_name_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phone'),
        ),
        migrations.AddField(
            model_name='product',
            name='colorway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('DS', 'DS'), ('VNDS', 'VNDS'), ('USED', 'USED')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(blank=True, choices=[('US', 'US'), ('W', 'W'), ('Y', 'Y'), ('GS', 'GS'), ('PS', 'PS'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UK', 'UK'), ('C', 'C')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phone')),
            ],
        ),
        migrations.CreateModel(
            name='AcquirementsDetail',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('boughtAt', models.DateTimeField(auto_now_add=True)),
                ('boughtPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('product', models.ManyToManyField(to='base.Product')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.provider')),
            ],
        ),
    ]
