# Generated by Django 3.2 on 2022-09-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220911_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirementsdetail',
            name='boughtAt',
            field=models.DateTimeField(),
        ),
    ]
