# Generated by Django 3.2 on 2022-09-12 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220911_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='phone',
        ),
        migrations.DeleteModel(
            name='AcquirementsDetail',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
