# Generated by Django 3.2 on 2022-09-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220911_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.phone')),
            ],
        ),
        migrations.CreateModel(
            name='AcquirementsDetail',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('boughtAt', models.DateTimeField()),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3, null=True)),
                ('boughtPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.provider')),
            ],
        ),
    ]
