# Generated by Django 3.2 on 2022-09-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20220911_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='amount_purchases',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='money_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30, null=True),
        ),
    ]
