# Generated by Django 3.2 on 2022-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220912_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquirementsdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('IN STOCK', 'IN STOCK'), ('SOLD', 'SOLD'), ('STOLEN', 'STOLEN'), ('TRADED', 'TRADED')], default='USD', max_length=20, null=True),
        ),
    ]
