# Generated by Django 3.2 on 2022-09-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_acquirementsdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquirementsdetail',
            name='location',
            field=models.CharField(blank=True, choices=[('DROPS', 'DROPS'), ('ICECLUB', 'ICECLUB'), ('USA.NICKY', 'USA.NICKY'), ('SPOT 1', 'SPOT 1'), ('SPOT 2', 'SPOT 2'), ('SPOT 3', 'SPOT 3')], default='USD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acquirementsdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('IN STOCK', 'IN STOCK'), ('SOLD', 'SOLD'), ('STOLEN', 'STOLEN'), ('TRADED', 'TRADED')], default='IN STOCK', max_length=20, null=True),
        ),
    ]
