# Generated by Django 3.2 on 2022-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220912_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirementsdetail',
            name='location',
            field=models.CharField(blank=True, choices=[('DROPS', 'DROPS'), ('ICECLUB', 'ICECLUB'), ('USA.NICKY', 'USA.NICKY'), ('SPOT 1', 'SPOT 1'), ('SPOT 2', 'SPOT 2'), ('SPOT 3', 'SPOT 3')], max_length=20, null=True),
        ),
    ]
