# Generated by Django 3.2 on 2022-09-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_acquirementsdetail_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50, null=True)),
                ('size_type', models.CharField(blank=True, choices=[('US', 'US'), ('W', 'W'), ('Y', 'Y'), ('GS', 'GS'), ('PS', 'PS'), ('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('UK', 'UK'), ('C', 'C')], max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='base.Size'),
        ),
    ]
