# Generated by Django 3.2 on 2022-09-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_product_colorway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
    ]
