# Generated by Django 3.2 on 2022-09-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.model'),
        ),
    ]
