# Generated by Django 3.2 on 2022-09-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20220914_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquirementsdetail',
            name='soldAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
