# Generated by Django 3.2 on 2022-09-18 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_acquirementsdetail_soldat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.FloatField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('discount_amount', models.FloatField()),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
