# Generated by Django 3.2 on 2022-09-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_discountcoupon_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.promotion'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
